@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package com.dtteam.dynamictreesplus.model.geometry;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;